# Generated by Django 5.1.1 on 2024-10-09 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("productService", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="title",
        ),
    ]
