# Generated by Django 5.1.1 on 2024-10-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productService", "0002_rename_name_product_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.FloatField()),
                ("count", models.IntegerField()),
            ],
        ),
    ]
