# Generated by Django 5.1.1 on 2024-10-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("productService", "0003_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(),
        ),
    ]
